### ISSUE TITLE
Use retriever to download PRISM data

### ISSUE THREAD

**Issue by ethanwhite** [weecology/bbs-forecasting#10]
`get_prism_data` currently uses the `prism` R package. Since we'll be combining data from lots of different sources let's keep the data acquisition part straight forward by using the retriever for everything.

I don't have strong opinions on using `prism` vs. Postgres for merging the data with BBS at the moment, but that may change as the number of different sources for predictors increases.

**Comment by ethanwhite** [comment]
There is currently a bug in `ecoretriever` blocking us from doing this directly inside of R. I have a PR in to fix it: https://github.com/ropensci/ecoretriever/pull/62

At that point `ecoretriever::download('PRISM', path='data/prismdata', sub_dir=TRUE)` should do the trick.

**Comment by davharris** [comment]
Do we still want to do this? Looks like the PR referenced above has been merged

**Comment by ethanwhite** [comment]
If it works seamlessly I'd love to swap in a retriever for the code in `download_prism()`. My recollection is that at the time I thought this would be as simple as replacing lines 13-19 in `download_prism()` with the above call to `ecoretriever`.

**Comment by ethanwhite** [comment]
No point trying to swap out data processing code at this point.
