### ISSUE TITLE
Explore how much work to switch to GIMMS 3 version 2

### ISSUE THREAD

**Issue by ethanwhite** [weecology/bbs-forecasting#109]

**Comment by sdtaylor** [comment]
I think it will take me a full day to do this and make sure it's all working correctly.

**Comment by ethanwhite** [comment]
At that time scale I'd say it's your call. I'm happy to just stick to what we have since that's our norm, but if you want to spend the extra day to get the additional two years I'm OK with that as well.

**Comment by sdtaylor** [comment]
I'd rather not unless #97 could really use another 2 years.

**Comment by ethanwhite** [comment]
No, I think 30 is sufficient there. Thanks for looking into this.
