### ISSUE TITLE
Add data on land cover as predictors

### ISSUE THREAD

**Issue by ethanwhite** [weecology/bbs-forecasting#11]
Ideally we'd like fairly finely resolved land cover data going back to the 1970s.

The [National Land Cover Database](http://www.mrlc.gov/) is one option, but its big limitation is that there are only 4 time points: 1992, 2001, 2006, 2011. If the algorithms are available we could think about processing the full time-series (though this could be a pretty massive computational task). We could also interpolate between the neighboring points. This has some risks, but I suspect that land cover change is gradual in most cases. It still leaves us without data prior to 1992 and post 2011. NLCD also only covers the United States.

Other sources of land cover data:
- https://lta.cr.usgs.gov/GLCC
- http://www.landfire.gov/
- https://lta.cr.usgs.gov/NLC
- http://eros.usgs.gov/land-cover

**Comment by ethanwhite** [comment]
I updated the description for this issue after having thought about the weakness of NLCD for this project.

**Comment by ethanwhite** [comment]
Most of the available land cover data appears to be generated using classification algorithms on remotely sensed data. This means that while it would be less informative biologically, we could also potentially just use the different components of the sensors and do feature selection related to our problem (e.g., using a neural net).

**Comment by davharris** [comment]
There could be advantages to this, but I suspect the loss of interpretability will prevent this from being worthwhile. Also, a lot of domain expertise went into cleaning up the data, and we could either miss it or spend a lot of time reinventing wheels. 

Dave

**Comment by sdtaylor** [comment]
It would be interesting to run land cover thru a model with other predictors and see if it actually comes out as significant.

**Comment by davharris** [comment]
In case I wasn't clear, I was replying to Ethan's comment from just before mine, not to the idea of using land cover in general.

I don't think there's any doubt that land cover would provide a valuable supplement to climate predictors for BBS.

**Comment by davharris** [comment]
Another limitation to NLCD, if I remember correctly, is that it doesn't include Canada.

**Comment by ethanwhite** [comment]
> Another limitation to NLCD, if I remember correctly, is that it doesn't include Canada.

Good point. I'll add that to that to the notes above.

**Comment by ethanwhite** [comment]
Figuring out the best datasets and approaches will be a good project for Josie once they start.
