### ISSUE TITLE
Explore using CMIP & constantish NDVI for making env forecasts

### ISSUE THREAD

**Issue by ethanwhite** [weecology/bbs-forecasting#110]
- [x] Look into getting and merging in CMIP data
- [ ] Explore fixing NDVI in environmental models

**Comment by sdtaylor** [comment]
For CMIP data we have a few choices to make. 

-How far out to go. CMIP5 goes to 2099
-Which scenario to use. They have different outputs for RCP 2.6, 4.5, 6.0, and 8.5. 8.5 is the worst case scenario.
-Dealing with ensembles. There are 10-20 different model outputs from various institution around the world, each with 1-5 runs based on slightly different initial conditions.

**Comment by sdtaylor** [comment]
I think for time period 2050 sounds like a reasonable number. anything beyond that will probably be terrible because we can't predict observers or ndvi.

for the ensembles the most straightforward way would be to average everything together to give our own models just a single set of bioclim vars to work with.

**Comment by ethanwhite** [comment]
@sdtaylor - those both sound good to me. As for the RCP choice, I don't have any strong feelings, but I think picking one of the middle two values seems reasonable as a middle of the road estimate.

**Comment by davharris** [comment]
What are our current thoughts about fixing NDVI?

**Comment by sdtaylor** [comment]
I think just the average value since the year 2000 or so.

**Comment by davharris** [comment]
To clarify, does that mean the following?

"During training, use the value for that year. Forecasts will be based on the average value from the last X years of the training set"

**Comment by sdtaylor** [comment]
Yes, but maybe:  
"For the forecasted years 2014-2050 we used near surface temperature and precipitation data from CMIP5 RCP6.0 models to calculate the bioclim variables. NDVI values were the site level mean from the years 2000-2013, and the observer was set as the last known observer at the site."

**Comment by davharris** [comment]
Ah, so this is just post-2013. Got it.

It might make more sense to make predictions based on the median observer. I don't think we really want to assume zero observer turnover between now and 2050.

**Comment by sdtaylor** [comment]
who would the median observer be?

**Comment by davharris** [comment]
It's what you get when you set the observer bias to zero

Dave

**Comment by sdtaylor** [comment]
Ok, that sounds good.

**Comment by sdtaylor** [comment]
Update on CMIP data. I think [this](http://gdo-dcp.ucllnl.org/downscaled_cmip_projections/) is the best source for CMIP5 data for us. This group does downscaling to 12x12km from the original 0.5 deg data and distributes only the variables hydrologists (and ecologists) care about, surface precip and temperature. I'm currently working on getting the 17 models aggregated to 1 as well as to the 40x40km resolution we're using.

**Comment by sdtaylor** [comment]
I'm going to make it so the cmip data is accessed via `get_bioclim_data(source='cmip5')`, while `get_bioclim_data()` defaults to the original prism data so nothing gets broken. Will probably add 1 more function called `get_future_env_data()` to aggregate other things for 2017+ forecasts.

**Comment by sdtaylor** [comment]
There is some overlap in the prism/cmip5 data so I can do some quick comparisons. These are the raw climate variables, each point is a single site/month. The temperature is *really* good. Precip is really variable in reanalysis data like this so it's probably the best we a hope for. 

![image](https://user-images.githubusercontent.com/12282062/27224584-e3bec04e-5263-11e7-9fae-9c3e074b2977.png)

And of the bioclim variables. each point is a site/year. The funky ones have precip incorporated somehow. 

![image](https://user-images.githubusercontent.com/12282062/27224826-35067e00-5265-11e7-9d32-d4cc586e02cd.png)

**Comment by ethanwhite** [comment]
Really interesting, the biased bioclim variables in particular. Thanks for doing this check. I definitely think there's a really interesting project or two to be done looking at integrating uncertainty in the future climate predictions into these kinds of forecasts

**Comment by sdtaylor** [comment]
There is an updated sqlite file on the T drive for using the updates in #128

**Comment by davharris** [comment]
Thanks @sdtaylor! I think I'll wait to re-run everything until the NDVI is also available, so that I can fit & predict to 2050 in one go.

**Comment by sdtaylor** [comment]
@davharris, cmip5 bioclim forecasts and the NDVI averages is now included in #129, let me know if that works for you. I'm not sure to incorporate the median observer into it.

**Comment by davharris** [comment]
Awesome. I can deal with the observer stuff.  Thanks!

**Comment by davharris** [comment]
I think this is solved in #129. Nice work @sdtaylor!
