### ISSUE TITLE
Make figures and tables

### ISSUE THREAD

**Issue by ethanwhite** [weecology/bbs-forecasting#111]
At our last meetings we planned out the following figures and tables for the ms:

- [x] Table 1: Model methods
- [x] Figure 1: Example time-series w/forecasts
- [x] Figure 2: Observed-predicted plot for 3 time lags
- [x] Figure 3: Time lag results figure (Main results)
- [ ] Figure 4: Violins of fit at 3 time lags
- [ ] Figure 5: Observation model figure

The sketches for each of these figures is below. If you are already working on or want to work on a figure just leave a note in the the comments (and maybe ping the Slack channel) to avoid duplicate work.

![2017-05-11 13 53 27](https://cloud.githubusercontent.com/assets/744427/26079610/55c36e10-3991-11e7-946e-bee53c1e5c5f.jpg)

![2017-05-11 13 53 21](https://cloud.githubusercontent.com/assets/744427/26079449/d0b07d8a-3990-11e7-9a8b-a51269828278.jpg)

New sketch for the observation model figure from 2017-05-18 meeting:

![img_0862](https://cloud.githubusercontent.com/assets/744427/26216380/daa9b516-3bd1-11e7-9920-86a18796efd6.JPG)

**Comment by davharris** [comment]
Table 1: 

|model             |environment |time |target                   |site_id |
|:-----------------|:-----------|:----|:------------------------|:-------|
|Naive             |X           |✔︎    |richness                 |✔︎       |
|Average           |X           |✔︎    |richness                 |✔︎       |
|Auto-ARIMA   |X            |✔︎    |richness                 |✔︎       |
|Random Forest SDM |✔︎           |X    |single species presence  |X       |
|Mistnet JSDM      |✔︎           |X    |full species composition |X       |
|GBM richness      |✔︎           |X    |richness                 |X       |

**Comment by sdtaylor** [comment]
working on fig 5.

**Comment by sdtaylor** [comment]
Figure 2

![image](https://cloud.githubusercontent.com/assets/12282062/26213354/b5b0c85e-3bc6-11e7-9ac1-868df0b822b1.png)

**Comment by davharris** [comment]
I think these are all finalized now.
