### ISSUE TITLE
On the disparity between observations and weather data 

### ISSUE THREAD

**Issue by sdtaylor** [weecology/bbs-forecasting#114]
@davharris  says:

Given that it's kind of weird to ask "how will next month's (June) weather affect what birds we'll find on today's transect run (in May)", it's probably worth adding a sentence pointing out that quirk of our data.

**Comment by sdtaylor** [comment]
I don't think this is an issue. Birds are present in a location because of long term climate trends, which are reflected in the bioclim variables. If some of the measurements (ie. precip in the wettest quarter) end up being in the fall, I suspect that it's still correlated with the climate the rest of the year.

**Comment by davharris** [comment]
If birds are doing everything based on long-term climate trends, then why are we using annual data? I think it's worth thinking about it some more. 

Dave

**Comment by ethanwhite** [comment]
I agree that it will definitely be correlated, but also agree with @davharris that we're using annual data to try to get at finer scale information and it does seem weird to use future data this way.

One option would be to slide the window for calculation to May 1 - April 30 to calculate the values over the previous year.

**Comment by sdtaylor** [comment]
Changing the window to end on April 30 is doable. Ending the year in the summer instead of the  winter is essentially what's done in the southern hemisphere.

**Comment by davharris** [comment]
Sounds good to me.  Does this line up with the boundary between "quarters" for the bioclim variables?

**Comment by sdtaylor** [comment]
No, having the window end in June or March would make it line up.

**Comment by ethanwhite** [comment]
I think June would be fine.

**Comment by sdtaylor** [comment]
do we want to do this with NDVI too? currently we have two NDVI vars. mean summer (may,june,july) and mean winter (dec, jan, feb).

**Comment by ethanwhite** [comment]
Yeah. My take would be to have summer for the year of the sample and winter for the previous winter, so e.g., for the 2012 bird data has may-july 2012 and dec 2011 - feb 2012. I'm also open to dropping July since that would be after most sampling is complete.

**Comment by sdtaylor** [comment]
I'd say drop july just to match the bioclim data.

**Comment by sdtaylor** [comment]
done in #115
