### ISSUE TITLE
NAs in "future" data

### ISSUE THREAD

**Issue by davharris** [weecology/bbs-forecasting#133]
I have NA for about 6% of the "future" bioclim data and about 2.5% of the NDVI data. Should I just throw those rows out, or is this a red flag we should investigate further?

**Comment by sdtaylor** [comment]
How are you calculating those?  

I count 1193 unique sites in the past/prism data with bio1 as na, compared to 833 in the future/cmip data. Both sources have 5061 unique sites total.  
The past/prism data doesn't include any canada sites, while the future/cmip data does include canada data, so I would expect the past data to have more NA.

**Comment by davharris** [comment]
I'm finding that there are 242 sites that had NAs in 2014 and 2015 (but had at least some non-NAs before). Each of these sites is missing all of its future bioclim data. I've listed them below.

I'm also finding a lot of rows in "future" data that have the year listed as 2051, and none of these have NDVI data.

Can you confirm?


```
c(2040L, 2041L, 2042L, 2070L, 2140L, 2141L, 2142L, 2217L, 11002L, 
11201L, 11210L, 11410L, 14004L, 14019L, 14038L, 14039L, 14045L, 
14050L, 14057L, 14075L, 14083L, 14099L, 14120L, 14123L, 14135L, 
14193L, 14345L, 18001L, 18006L, 18013L, 21001L, 21002L, 21006L, 
21007L, 21009L, 21010L, 21105L, 21107L, 25002L, 25007L, 25009L, 
25011L, 25016L, 25018L, 25025L, 25027L, 25032L, 25036L, 25039L, 
25051L, 25062L, 25064L, 25070L, 25075L, 25077L, 25078L, 25079L, 
25080L, 25083L, 25085L, 25086L, 25087L, 25088L, 25109L, 25116L, 
25132L, 25135L, 25170L, 25175L, 25178L, 25180L, 25183L, 25283L, 
27001L, 27056L, 27301L, 27305L, 35001L, 35101L, 35201L, 35301L, 
42001L, 42002L, 42004L, 42006L, 42008L, 42030L, 42031L, 42051L, 
42101L, 42102L, 42105L, 42108L, 42208L, 42311L, 42312L, 42411L, 
44002L, 44004L, 44005L, 44017L, 44023L, 44024L, 44025L, 44028L, 
44117L, 44308L, 46020L, 46027L, 46035L, 46036L, 46037L, 46041L, 
46042L, 46043L, 46048L, 46049L, 46058L, 46149L, 47001L, 47002L, 
47003L, 47004L, 47006L, 47007L, 47102L, 47104L, 49001L, 49002L, 
49004L, 49006L, 49009L, 49014L, 49015L, 49017L, 49022L, 49023L, 
49025L, 49026L, 49029L, 49030L, 49040L, 49041L, 49042L, 49043L, 
49059L, 49062L, 49064L, 49070L, 49130L, 49143L, 49162L, 49230L, 
50031L, 50032L, 50034L, 50042L, 50047L, 50048L, 51029L, 51229L, 
56036L, 59002L, 59004L, 59005L, 59013L, 59025L, 59028L, 59029L, 
59030L, 59031L, 59032L, 59104L, 59131L, 59132L, 59204L, 59231L, 
61001L, 61002L, 61003L, 61004L, 61005L, 61053L, 61061L, 61063L, 
61065L, 61069L, 61070L, 61109L, 61169L, 63002L, 63003L, 63007L, 
63029L, 63107L, 63202L, 63204L, 63208L, 63229L, 63306L, 63329L, 
66006L, 66007L, 66107L, 66113L, 68004L, 68036L, 68065L, 68253L, 
69017L, 69117L, 77001L, 77002L, 80005L, 80022L, 80122L, 83001L, 
83006L, 83011L, 83020L, 83021L, 83022L, 83306L, 87022L, 87023L, 
88010L, 88029L, 88032L, 88045L, 88048L, 89001L, 89009L, 89027L, 
89066L, 89072L, 91005L, 91030L, 91048L, 91049L, 91062L, 91063L, 
91301L)
```

**Comment by davharris** [comment]
Oh, 2014 and 2015 don't have NDVI data for *any* of the sites (because that's the default argument to `get_env_data`). I was hoping that would be diagnostic of where the problem was coming from, but apparently not.

**Comment by sdtaylor** [comment]
Thanks @davharris. All those sites are along the coast or great lakes area. CMIP data has different edges than PRISM, so some of them are getting NA's because of NA CMIP cells. It's being made worse by the aggregation being done, so I should be able to get most of them back by fixing that.

**Comment by davharris** [comment]
Thanks @sdtaylor!

**Comment by davharris** [comment]
❤️

**Comment by sdtaylor** [comment]
I've updated the sqlite data file on the T drive to reflect this.
