### ISSUE TITLE
Citation details for Jarvis 2008

### ISSUE THREAD

**Issue by ethanwhite** [weecology/bbs-forecasting#134]
I'm in the process of revising the ms at the moment and working on references on my way through. There's a citation for Jarvis 2008 in reference to the elevation data that I couldn't quickly track down on scholar. @sdtaylor - do you know what the specific reference is for that (since I'm guessing you added it)?

**Comment by sdtaylor** [comment]
Yep, here's the bibtex for it. From [here](http://www.cgiar-csi.org/data/srtm-90m-digital-elevation-database-v4-1#citation) 

```
@misc{jarvis2008,
annote = {SRTM 90 elevation data},
author = {Jarvis, A. and Reuter, H.I. and Nelson, A. and Guevara, E.},
mendeley-groups = {Software/Data},
title = {{Hole-filled SRTM for the globe Version 4, available from the CGIAR-CSI SRTM 90m Database}},
url = {http:/srtm.csi.cgiar.org},
year = {2008}
}
```

**Comment by ethanwhite** [comment]
Perfect. Thanks!
