### ISSUE TITLE
Interpret auto ARIMA fit values and add to supplement 

### ISSUE THREAD

**Issue by ethanwhite** [weecology/bbs-forecasting#135]
As @davharris notes in the ms, we should record the values for the `auto.arima` fits so that they can be interpreted.

We should also look at what proportion of these fits end up being equivalent to the naive model, equivalent to the average model, and something more complicated.

**Comment by davharris** [comment]
I'm not entirely sure how to read the auto.arima outputs, but here's what I get on a subset of the data (including observer effects).  I'll report more complete numbers once everything has run on the gator, but this should be qualitatively correct.

* 16% have nothing listed under "coefs." Not sure what that means
* 59% have just an intercept. I think that makes them equivalent to the "average" model
* 6% have just AR1. I think that makes them like the "naive" model
* 7.5% have AR1 and intercept, which makes them a hybrid of the two.
* 7% have just MA1 or MA1 + intercept.
* There's a modestly long tail of other combinations, including things like AR2, MA2, drift, and occasionally even AR3

**Comment by davharris** [comment]
And here's the code:

```
forecasts %>% 
    filter(model == "auto.arima", year == settings$future_year) %>% 
    pull(coef_names) %>% 
    map_chr(paste, collapse = ", ") %>% 
    table() %>% 
    sort(decreasing = TRUE)
```
