### ISSUE TITLE
Summary stat for limited change in richness

### ISSUE THREAD

**Issue by ethanwhite** [weecology/bbs-forecasting#137]
There is a location in the Discussion where we need to note that richness hasn't changed much. We could list the low variance as mentioned earlier in the paper or something else.

**Comment by davharris** [comment]
I think this is covered. The paper says:

>On average, the Breeding Bird Survey sites used in this study show little change in richness [site-level SD of 3.6 species, after controlling for differences among observers; see also @lasorte2005]

Do we want to add anything specifically about directional change?

**Comment by ethanwhite** [comment]
This is fine with me.
