### ISSUE TITLE
Get data on climate forecasts

### ISSUE THREAD

**Issue by ethanwhite** [weecology/bbs-forecasting#14]
To start making actual forecasts using models that involved exogenous variables, we will need forecasts for those variables. This issue is a place for us to start looking into options for doing this.

**Comment by sdtaylor** [comment]
There is *so* much information on climate/weather predictions available. There are many different groups, a lot of them doing things that overlap, a lot specializing on specific regions or processes, a lot summarizing/ensembling what other have done. etc. 

It would be really beneficial if we could get a crash course in climate modelling. How they are made, what their predictions actually comprise and what they can and can't be used for. 

That being said, here are two links within NOAA that we'll probably end up pulling data from some day. 

[NOAA Model Datasets](https://www.ncdc.noaa.gov/data-access/model-data/model-datasets) - Lots of datasets from various weather/climate models. Some of them are especially interesting because that have historic forecasts which can be judged against what actually happened. 

[NCEP EMC](http://www.emc.ncep.noaa.gov/) - 
>National Centers For Environmental Prediction's Environmental Modeling Center. The Environmental Modeling Center is responsible for the enhancements, transitions-to-operations, and maintenance of more than 20 numerical prediction systems comprising NCEP's operational production suite.

**Comment by sdtaylor** [comment]
This R package will probably be useful for this. It's a wrapper for accessing the API of a bunch of NOAA data.

https://github.com/ropensci/rnoaa

**Comment by sdtaylor** [comment]
**Short Term Forecasts**

[Global Ensemble Forecast Systems (GEFS)](https://www.ncdc.noaa.gov/data-access/model-data/model-datasets/global-ensemble-forecast-system-gefs)
Ensemble forecast of 21 different global models. Resolution of 1-2.5 deg. Released 4 times daily, each one making forecasts for 0-16 days ahead at 6 hour timesteps. Has confidence intervals.

[Global Forecast System (GFS)](https://www.ncdc.noaa.gov/data-access/model-data/model-datasets/global-forcast-system-gfs)
Single model global forecasts. 0.5 or 1 deg. released 4 times daily, making forecasts at 3 hour timesteps out to 10 days, and 12 timesteps 10-16 days.
Past a few hours it does not have forecasts for on the ground variables (temp & precip) directly.
NWS home page for GFS http://www.emc.ncep.noaa.gov/index.php?branch=GFS

[Experimental Forecast with Confidence Intervals](http://moe.met.fsu.edu/confidence/)
This group at FSU is using GFS ensembles to make confidence intervals of short term forecasts (up to 7 days out). Doesn't look like they make data available.

**Long term forecasts**

[CFSv2 Operational Forecasts with CI's](https://www.ncdc.noaa.gov/data-access/model-data/model-datasets/climate-forecast-system-version2-cfsv2#CFSv2%20Operational%20Forecasts)
0.5 deg global forecasts, released 4 times daily. hourly timesteps out to 9 months
NWS uses of the CFFv2 here - http://www.cpc.ncep.noaa.gov/products/CFSv2/CFSv2seasonal.shtml

[Abatzogula Lab downscaled 7 month forecast](http://climate.northwestknowledge.net/RangelandForecast/download.php)
Uses the [North American Ensemble](http://www.cpc.ncep.noaa.gov/products/NMME/) project do create downscaled (4km) grid of the western us daily precip and temp forecasts up to 7 months out. Really nice visuals and website tools. Also looks like easy access to actual data.

[NWS Climate Prediction Center three month outlooks.](http://www.cpc.ncep.noaa.gov/products/predictions/90day/)
forecasts 3 month mean temp & total precip for up to 12.5 months into the future. old old old website. There is little actual data to download, just 90's era maps. There is "GIS data", but it's only shapefiles showing the probability of exceeding the long term average, and doesn't seem to even match the old school maps.

[European Centre for Medium-Range Weather Forecasts](http://www.ecmwf.int/en/forecasts/datasets)
Hosts many different forecast datasets with global coverage from several days to 7 months out. Includes ensemble forecasts. Some data is free without a login, some available for research use only with a possible small fee.

[International Research Institude for Climate & Society](http://iri.columbia.edu/about-us/what-is-iri/)
Based at columbia univ. Hosts a lot of climate data in a very confusing website. Most of the NOAA forecast data is hosted here.

[APCC Climate Center](http://www.apcc21.org/main.do?lang=en)
Asian Pacific Partnership of 21 countries (including USA) consolidates other climate forecasts and makes an ensemble. Data page [here](http://cis.apcc21.org/)

**Comment by ethanwhite** [comment]
Done using CMIP5 so closing for now. Definitely interested in the shorter term data forecasting efforts.
