### ISSUE TITLE
citations and acknowledgments

### ISSUE THREAD

**Issue by sdtaylor** [weecology/bbs-forecasting#142]
### Data
- [x] BBS
- [x] PRISM
- [x] NDVI (NDVI3g dataset)
- [x] Elevation
- [x] CMIP5
       *Requests acknowledgement and a special table listing all the models used (can be put in supplement)
- [x] Downscaled CMIP5, from [here](http://gdo-dcp.ucllnl.org/downscaled_cmip_projections/dcpInterface.html) 

## Software
- [x] R
- [x] raster
- [x] retriever
- [x] tidyverse?

**Comment by ethanwhite** [comment]
I'll work of adding some of these now if you (@sdtaylor) aren't currently working on them.

**Comment by ethanwhite** [comment]
@sdtaylor - can you add a few sentences to Data section (probably at the end of the environmental data paragraph or in a short new paragraph) that describes the CIMP5 data usage? I also couldn't figure out what the really wanted with the table. We could potentially include that information in the text as well if there weren't going to be too many rows in the table.

**Comment by sdtaylor** [comment]
Yep

**Comment by davharris** [comment]
👍
