### ISSUE TITLE
Pick a journal

### ISSUE THREAD

**Issue by davharris** [weecology/bbs-forecasting#152]
Four good options:

* PeerJ
* Ecology
* The American Naturalist
* eLife

**Comment by ethanwhite** [comment]
@sdtaylor - any thoughts on this. I have a personal preference for one of the fully open journals, but am always happy to defer to students on these decisions.

**Comment by sdtaylor** [comment]
Am I right in thinking we'd get a lot of pushback from Ecology for saying "SDM's are no better than site averages"?

**Comment by ethanwhite** [comment]
@sdtaylor - we're probably going to get a lot of push back on that regardless of where we submit...

**Comment by sdtaylor** [comment]
In that case I'm ok with any of them except perhaps elife, only because I can't remember ever reading a paper from there. And skimming the ecology section it mostly looks like evolution and/or genetics papers.

**Comment by ethanwhite** [comment]
We've decided on PeerJ barring any changes of heart.
