### ISSUE TITLE
Should the time-series plots show models incorporating observer effects

### ISSUE THREAD

**Issue by ethanwhite** [weecology/bbs-forecasting#162]
It looks like our example figure is using the non-observer corrected values, is that correct? If so it seems like keeping with the philosophy of "the right way to do this is with the observer model so everything we show is with it unless we're exploring it's influence" would mean we should use the observer correction in these examples.

I can see how it could be confusing since the Average model won't line up with the literal average, but I think that could be addressed with a note in the legend.

Happy to discuss more since it looks like we were thinking about this differently.

**Comment by davharris** [comment]
This is an example of a plot we could show with `use_obs_model` turned on. I specifically chose a site (labeled in the upper-left) with only one observer over the whole time series, so we don't have to confuse the reader by introducing too much at once.

![model_predictions](https://user-images.githubusercontent.com/843017/29377265-4b896080-8289-11e7-863b-561219e8556f.png)

It still shows:

1) average has different mean and CI than naive
2) environmental models are poor
3) auto.arima ends up essentially replicating average
4) rf has narrow CIs

**Comment by ethanwhite** [comment]
Perfect. The idea of picking a model with only one observer the whole time was brilliant.
