### ISSUE TITLE
Title discussion

### ISSUE THREAD

**Issue by ethanwhite** [weecology/bbs-forecasting#164]
I'm still not totally happy with the title so I'm opening an issue for us to kick around and settle on options. Here are a couple of options to get us started.

* Forecasting biodiversity in breeding birds using best practices
* Forecasting species richness in breeding birds using best practices

**Comment by davharris** [comment]
Could you clarify what you don't like about the current one?

I think you're right to drop *changes in*. What I like about something more like *Best practices for forecasting biodiversity: an example using breeding birds* is that it specifies that the best practices are for forecasting biodiversity, rather than for ecology in general or for forecasting birds in particular.

**Comment by ethanwhite** [comment]
I guess for me it sets the paper up more as focusing as on the best practices *per se* and less on the analysis and my read of the way we've ended up writing it is that the balance is the other way around. In other words, for the current title I'd expect a paper that primarily focused on walking through each of the best practices in detail and then provided examples/case studies using them. This is magnified by the colon.

**Comment by davharris** [comment]
Okay, I agree with that. I'll keep thinking about it.

**Comment by davharris** [comment]
How about this?

>Forecasting biodiversity in breeding birds: best practices and limitations

**Comment by ethanwhite** [comment]
My brain naturally reads the stuff after the colon as kind of a subtitle here and so I'd naturally associate this with more of an ideas piece, but I'm OK with it as a compromise.

**Comment by davharris** [comment]
Okay, fair point.  I'll use

> Forecasting biodiversity in breeding birds using best practices

Sorry for going back-and-forth on this so many times...

**Comment by ethanwhite** [comment]
No problem at all. In the modern era I think titles are really important and so I think trying out a bunch of different options and going back-and-forth to get the best one is a good use of time.
