### ISSUE TITLE
Number of test points

### ISSUE THREAD

**Issue by ethanwhite** [weecology/bbs-forecasting#165]
This ms currently lists 22 test and 9 training points, but the figures show 10 training points (2004-2013), so I think this should be 22 and 10.

**Comment by davharris** [comment]
You're right, I can't count. On the flip side, there are some places we talk about 20 and 30 years, which should be 22 and 32, I think.

**Comment by ethanwhite** [comment]
Yep. Let's get those as well.

**Comment by davharris** [comment]
Fixed in #168
