### ISSUE TITLE
missing important citation information from "note" section

### ISSUE THREAD

**Issue by davharris** [weecology/bbs-forecasting#180]
If we had a CSL style file that included the "note" section, we could include important information about our R packages, e.g. "R package version 2.1.1".

Alternatively, we could rename the "note" section in the R packages to something that our current CSL file would put in the right place.

**Comment by sdtaylor** [comment]
We could put them in the title. That's how it's done is some of the R refs in elitas recent peerj paper. https://peerj.com/articles/2823/

**Comment by davharris** [comment]
Is there an automated way to do that, or should we do it by hand?

**Comment by sdtaylor** [comment]
There aren't that many, so probably by hand is a quicker way than finding/inventing a way to do it in the rendering.
