### ISSUE TITLE
Observer effects figure no longer provide info for several discussion points?

### ISSUE THREAD

**Issue by ethanwhite** [weecology/bbs-forecasting#184]
In redoing the observer effects figures we seem to have lost evidence for the following. Is that correct?

> Accounting for differences in observers reduced the average error in our point
estimates and also **improved the coverage of the confidence interval**.

> In addition, **controlling for observer effects resulted in changes in which models performed best**, most notably reducing the relative performance of the naive model's point estimates

**Comment by sdtaylor** [comment]
Are you saying these statements are no longer supported, or that with the way the figures are now these statements can't be inferred? I feel like with the current state of #175 it's the latter.

**Comment by ethanwhite** [comment]
Yes, the latter.

**Comment by davharris** [comment]
Good catch. I'll see if we can add another panel somewhere to address this directly.

**Comment by davharris** [comment]
What do you think about this plot? Arrows show how the summary stats change when we `include observer_id` in our predictions. I think this could probably replace the observer violins in the main text, bumping them to an appendix.

![image](https://user-images.githubusercontent.com/843017/29884443-8a3d9316-8d81-11e7-9b2c-48681290be16.png)

**Comment by sdtaylor** [comment]
Is the length of the line the magnitude of the change? So the tip of the error is the new mean?

**Comment by davharris** [comment]
Exactly.

**Comment by sdtaylor** [comment]
I like it. It seems kinda simple, like more info could be added somehow. but it might be good to keep it simple.

**Comment by davharris** [comment]
The other option that comes to mind is a set of slopegraphs, like this, but with use_obs_model on the x-axis https://pbs.twimg.com/media/CCVNZ0pUAAAUQjT.png

**Comment by ethanwhite** [comment]
I really like this. We loose the information about how overlapping the distributions are, but that can just be stated in the text and this does a nice job of clearly showing the key points we are trying to make.

**Comment by davharris** [comment]
Great. To clarify, you like the idea of replacing the violins with the arrows?

**Comment by ethanwhite** [comment]
Yep. I like the detailed information in the violins, but in this case I think the improved communication makes it worthwhile to lose that.

**Comment by sdtaylor** [comment]
Just one thing. Maybe put a faded dot at the beginning of the line and a solid one at the arrow tip to highlight exactly where the means are.

**Comment by davharris** [comment]
I think that the smaller black arrows solve the problem @sdtaylor alluded to for showing exactly where the means are, without coving the arrows in blobby points (see below).

Any objections if I close this one too?

![obs_arrows](https://user-images.githubusercontent.com/843017/30175320-1872feb4-93cc-11e7-8c3c-55cb32d0c23b.png)

**Comment by sdtaylor** [comment]
No objections from me.

**Comment by ethanwhite** [comment]
👍
