### ISSUE TITLE
Appendices?

### ISSUE THREAD

**Issue by davharris** [weecology/bbs-forecasting#194]
So far, I think we've talked about including the following in appendices/supplements:

- [ ] More information on the deviance associated with the stacked SDMs (currently summarized in `figures/rf2.png`: the median prediction benefits slightly from having a concentrated predictive distribution, but fixing the tails of the distributions outweighs this on average)

- [ ]  Observer violins, so readers can see that observer effects sometimes help and sometimes hurt, with large effects in both directions

- [ ]  Observer turnover (e.g. `figures/observer_uncertainty.png`)

Do we want to include all of these? Am I missing anything else?

**Comment by ethanwhite** [comment]
I'm fine with including these but also fine with not doing so. Whatever you think is best. I can't think of anything else to add.

**Comment by sdtaylor** [comment]
paper is published
