### ISSUE TITLE
Keywords

### ISSUE THREAD

**Issue by davharris** [weecology/bbs-forecasting#195]
We get 10.  Here are some I came up with: 

Current list:

* birds
* breeding bird survey
* species richness
* biodiversity
* forecasting
* prediction
* climate change
* species distribution model
* time series
* space-for-time substitution

Additional options:

* macroecological model

**Comment by ethanwhite** [comment]
Looks great. I'd cut "macroecological model" to get to 10 if it was me since I don't think that term gets used much.

**Comment by davharris** [comment]
Okay, going ahead with the other 10.
