### ISSUE TITLE
Split PRISM aquistition and bioclim processing

### ISSUE THREAD

**Issue by ethanwhite** [weecology/bbs-forecasting#20]
This will let us make the `make` file more granular.

**Comment by sdtaylor** [comment]
Want to extend this to the NDVI data too?

**Comment by ethanwhite** [comment]
Sure, if it's not too much trouble.

**Comment by sdtaylor** [comment]
So this is essentially creating 2 new files. One for downloading, storing, and retrieving the prism data. One for processing, storing, and retrieving the bioclim data. 

It also creates the need for a config file to store things like the sqlite database in a single spot.

**Comment by ethanwhite** [comment]
@sdtaylor and I decided that this was overkill for the moment and we'll just go with one script for processing each major dataset and in the main file check to see if the dataset exists and if not then trigger the script to build it.
