### ISSUE TITLE
mini cover letter

### ISSUE THREAD

**Issue by davharris** [weecology/bbs-forecasting#202]
PeerJ wants us to "Enter a [280-character] message explaining why a reviewer should review your article. It will be included in the email inviting them to review. Describe interesting, specific or unique aspects of the work." It's basically a mini cover letter.

PeerJ's example:

>I believe you will enjoy reviewing this work because ~our Mitogenomic studies on Bryophyte genus Orthotricum results present a substantial change from the traditional taxon view~. We look forward to improving our article with your feedback. Thank you.

One possibility for the crossed-out bit:

>it compares a suite of different ecological models for forecasting biodiversity to simple baselines on a long-term data set.

If no one objects, I'll probably go ahead with that wording or something similar.

**Comment by sdtaylor** [comment]
Is this and the title all they get to decide? What about the abstract?

**Comment by davharris** [comment]
As of 2014, PeerJ sent out the title, abstract, and author list. That's what other journals do as well. I assume this hasn't changed, but don't know for sure.

**Comment by sdtaylor** [comment]
I'm fine with this then. I feel like the abstract will be what people make
up their mind with.

**Comment by ethanwhite** [comment]
:+1:
