### ISSUE TITLE
CMIP question

### ISSUE THREAD

**Issue by davharris** [weecology/bbs-forecasting#214]
Shawn, can you answer this from Ward's review?

Line 124: I’m not as familiar with terrestrial projections, but are the CMIP5 projections relatively unbiased / precise when compared to recent data?

**Comment by sdtaylor** [comment]
How's this? It seems like they are just curious, so I'm not sure if it's worth a change in the text. If you think so, then a better comment may be that downscaled CMIP5 projects are essentially the only weather/climate forecast available past a year lead time. 

> The accuracy of CMIP5 models varies by the variable considered. Temperature is represented very well over North America. Precipitation is challenging, especially over mountainous terrain, but the CMIP5 ensemble represents precipitation across North America relatively well [@koutroulis]. 

```
@article{koutroulis2016,
  title={Evaluation of precipitation and temperature simulation performance of the CMIP3 and CMIP5 historical experiments},
  author={Koutroulis, AG and Grillakis, MG and Tsanis, IK and Papadimitriou, L},
  journal={Climate Dynamics},
  volume={47},
  number={5-6},
  pages={1881--1898},
  year={2016},
  publisher={Springer}
}
```

**Comment by ethanwhite** [comment]
LGTM and I agree that this could just go in the response letter.

**Comment by sdtaylor** [comment]
#215
