### ISSUE TITLE
add config file

### ISSUE THREAD

**Issue by sdtaylor** [weecology/bbs-forecasting#22]
Add config.R file for common variables like: years of analysis and path to sqlite database file,.

**Comment by davharris** [comment]
I like this idea.  Here are the config variables I was able to find.  Any additions/amendments?

```
start_yr  1982
end_yr = 2013
min_num_yrs = 25
mc.cores = 8
n_test_years = 5
db_location = "data/bbsforecasting.sqlite"
```

**Comment by sdtaylor** [comment]
-a database connection for sqlite
-various data paths
  gimms_data
  prism_data

**Comment by davharris** [comment]
Any interest in adding the config file stuff you mentioned, @sdtaylor? I put some stuff in `settings.yaml` already (variables, years, etc.) but no database stuff.

**Comment by sdtaylor** [comment]
Yeah, the big thing is paths to data files which are hard coded in a lot of places, I'll go through and clean it up.

**Comment by sdtaylor** [comment]
I'm looking thru and trying to figure out how best to do this. I think the "proper" way would be to put hooks in essentially every data function call. Does that seem worth it? I don't see our data structure really changing, or the few people who might want to reproduce this changing it.

**Comment by davharris** [comment]
Thanks for looking into this.  Those are good points.  I'll close the issue.
