### ISSUE TITLE
Deviance figure for Supplement?

### ISSUE THREAD

**Issue by davharris** [weecology/bbs-forecasting#231]
Is a figure like this useful for explaining why mean deviance captures errors in both the point estimates (x axis) and in uncertainty (y axis)? The optimal combination of predicted mean and variance is at the "x".

Ward's confusion re: line 249 indicates that it might be useful in the Supplement, even for fairly advanced readers.

![image](https://user-images.githubusercontent.com/843017/33799419-437ea678-dcf9-11e7-8b09-cab696270fcc.png)

**Comment by ethanwhite** [comment]
I think this would confuse me more without a fair bit of walking me (as a reader) through it.

**Comment by sdtaylor** [comment]
didn't we discuss Ward just being hung up on our use of "precision" in describing deviance?

**Comment by davharris** [comment]
@sdtaylor That's right, thanks. I'll close this and fix it.
