### ISSUE TITLE
Add ARIMA forecasts with exogenous predictors

### ISSUE THREAD

**Issue by ethanwhite** [weecology/bbs-forecasting#24]
This happens in `auto.arima` using the optional `xreg` argument.

**Comment by ethanwhite** [comment]
I implemented this for a single exogenous predictor (annual NDVI) before my talk in Wyoming. Still need to explore how to do it for multiple exogenous predictors. We won't be able to dump all of the exogenous predictors we have into these simple models because we only have 20 time points to fit them to, so we'd either need to include limited subsets and do model selection at each site, or perhaps pick the most important features from the spatial models.

**Comment by davharris** [comment]
At our meeting last week, the consensus seemed to be that we'd use the 3 most "important" variables according to some metric (if I remember correctly).

How does elevation, bio_5, and ndvi_sum sound (based on [@sdtaylor's figure](https://github.com/weecology/bbs-forecasting/issues/55#issuecomment-250186761))? That gives us climate, topography, and greenness.

**Comment by ethanwhite** [comment]
Sounds good to me.
