### ISSUE TITLE
BBS quality criteria

### ISSUE THREAD

**Issue by davharris** [weecology/bbs-forecasting#246]
Editor wants us to clarify which surveys we excluded. Is there a good reference for this?

**Comment by ethanwhite** [comment]
Do you mean what the rules are for the 0/1 quality code?

**Comment by davharris** [comment]
Maybe? Like route type, weather, runtype, etc. 

Dave

**Comment by ethanwhite** [comment]
The surveys we excluded were based on BBS's runtype code:

> Runtype = 0 indicates that the data were not collected according to prescribed methods and/or were collected during unsuitable weather conditions.

ftp://ftpext.usgs.gov/pub/er/md/laurel/BBS/DataFiles/MetaData-NABBS_Dataset_1966-2016_v2016_0.xml

Is that information and source sufficient?

**Comment by ethanwhite** [comment]
Oh, and we also check  RPID = 101, which is just a standard BBS survey.

**Comment by sdtaylor** [comment]
Not following protocol or having bad weather sums it up, there are more details here ftp://ftpext.usgs.gov/pub/er/md/laurel/BBS/DataFiles/runtype.txt

**Comment by davharris** [comment]
Thanks Shawn! I was looking for that information but checked a few of the wrong files. Can we just link to that, or will we need to do more?

**Comment by ethanwhite** [comment]
I would summarize it as something like "either the standard protocols were not followed or weather conditions were not appropriate for obtaining and accurate sample" and then provide the link to the document @sdtaylor posted.

**Comment by sdtaylor** [comment]
paper is published
