### ISSUE TITLE
final editors to do list

### ISSUE THREAD

**Issue by sdtaylor** [weecology/bbs-forecasting#247]
line 265
Variance in species richness within sites 263 was lower than predicted by several common count models, such as the Poisson or 264 binomial (i.e. richness was underdispersed for individual sites), ~so these count models would have had difficulty fitting the data~ (cf. Calabrese et al. 2014)

editor suggests: so fitting the data is unlikely by these models. 

The suggestion just sounds weird to me

---
elaborate on figure 3B results

---

line 557 (box entry 4)

Original: 
Investing time in identifying and acquiring better predictor variables may have at least as many benefits as using more sophisticated modeling techniques (Kent et al. 2014).

Editor suggests: 
Investing time in identifying and acquiring better predictor variables may _often provide better results than simply_ using more sophisticated modeling techniques (Kent et al. 2014).

This rewording makes acquiring better predictors potentially better than what Kent says it is.

**Comment by ethanwhite** [comment]
I agree that both of the edits @sdtaylor doesn't like are questionable and change the meaning. I suggest that we don't make them.

**Comment by davharris** [comment]
Agreed. I was struggling a bit with the first one, so I'm glad I'm not the only one.

**Comment by sdtaylor** [comment]
published
