### ISSUE TITLE
Add post-2013 NDVI data

### ISSUE THREAD

**Issue by ethanwhite** [weecology/bbs-forecasting#25]
The GIMMS NDVI data we are using at the moment is only available through 2013. We need to fill this in moving forward, probably using MODIS or LTDR.

From #7:

> [LTDR](http://ltdr.nascom.nasa.gov/cgi-bin/ltdr/ltdrPage.cgi) appears to provide daily NDVI data back to 1981 using a combination of AVHRR and MODIS data. Data is available [via FTP](ftp://ltdr.nascom.nasa.gov/allData/) as one `hdf` file/day (25-150 MB/file depending on the satellite) and are split up by satellite (with different satellites covering different time periods). The NDVI data is in the AVH13C1 files. [Description of the NDVI product](http://ltdr.nascom.nasa.gov/ltdr/docs/AVHRR_LTDR_V4_Document.pdf). Unfortunately these are daily data which would force us to do the compositing ourselves.

**Comment by sdtaylor** [comment]
From [Intercomparison of Seven NDVI Products over the United States and Mexico](http://www.mdpi.com/2072-4292/6/2/1057/htm): GIMMS 3g and MODIS NDVI disagree some in mountainous and arid terrain but on the continental scale they have nearly a 1:1 relationship. This paper averaged over 10 days and ~15km, so if we average cells over 40km and several weeks at the peak of summer I'd feel comfortable using GIMMS and MODIS together.

**Comment by ethanwhite** [comment]
Sounds good to me. If possible it seems ideal to make the MODIS data into monthly values so that it matches up in structure with the GIMMS data. Are you up for creating a MODIS NDVI table that matches the GIMMS one?

We had some of the necessary code back when we were using just MODIS:
https://github.com/weecology/bbs-forecasting/blob/b52b7dcf8a63503b34de31a289b0ad4af81e1ff2/get_ndvi_data.R

**Comment by sdtaylor** [comment]
Yeah, should be easy enough.

**Comment by ethanwhite** [comment]
> But the new GIMMS data is being used to calculate summer, winter, and annual ndvi. Would you like the entire year's worth of MODIS now? 

Yes, we should get it at the monthly level to line up with what we have with GIMMS and give us the most flexibility down the line.

> fyi for 4900 sites it will take foooooorever to download. 

Yeah, that's part of the reason I'd originally just grabbed mid-summer :smile:. We should run this either on Serenity or the HiperGator.

> The MODIS data will fill in 2013-2015, but I also think we should get MODIS for 2010-2013 as well. Then it can be used for a quick comparison with the GIMMS data. 

Totally agree. In fact I think we might as well go all the way back to the beginning of the MODIS data. That will give us ~13 years of overlap to re-demonstrate the match and build a model for any adjustments we decide later that we need to make.

**Comment by sdtaylor** [comment]
I'm having a lot of issues with this. MODSTools takes forever because the server handling requests at oak ridge takes forever. The server will also only processes 10 dates for a single location at a time. It also sporadically times out, sends empty data, and/or a server busy signal for which MODISTools has limited error logging. 

At the moment it would be much easier to just download all north american modis tiles myself and extract the data.

**Comment by ethanwhite** [comment]
> At the moment it would be much easier to just download all north american modis tiles myself and extract the data.

Sorry this turned out to be a lot more work than expected. I have no attachment to MODISTools, so feel free to tackle this however is best for you. I'd love to have MODIS tiles in the retriever as well, so one option would be a add a retriever script to download all of the tiles and then process them locally however you prefer.

**Comment by ethanwhite** [comment]
This is an example of a retriever script that downloads all of the bioclim data:
https://github.com/weecology/retriever/blob/master/scripts/bioclim_2pt5.py

**Comment by ethanwhite** [comment]
The new release of the GIMMs package lets us do this, but it's too late in the process to start changing underlying data. Will use the new GIMMs data for the next project.
