### ISSUE TITLE
Add data on bodies of water

### ISSUE THREAD

**Issue by ethanwhite** [weecology/bbs-forecasting#28]
As an alternative to excluding water birds @davharris has suggested adding something like the proportion of area with a 40km buffer that is water as a predictor for the spatial models (and possibly the temporal ones if this changes much over the time period of the data, which it might).

**Comment by davharris** [comment]
I found the [North American Land Change Monitoring System (NALCMS)](http://www.cec.org/tools-and-resources/map-files/land-cover-2005) data, and believe that I've successfully defeated the projection/coordinate system.

It occurred to me that now would be a good time to ask:

1) Is this the best data set to use for water (keeping in mind that we need to include Canada, and things like the national land cover database won't work)?

2) While I'm at it, do we want to include any of the other land cover categories too? Should I just include all of them?

**Comment by ethanwhite** [comment]
Initial thoughts:

> 1) Is this the best data set to use for water (keeping in mind that we need to include Canada, and things like the national land cover database won't work)?

At the moment we've actually been restricting analysis to the contiguous US because that is where the PRISM (and possibly GIMMS) data is restricted to. It would definitely be better to include Canada & Alaska, but we aren't there at the moment. A lot of US government derived products are limited to the contiguous US.

In some areas of the US water levels will change a lot from year to year, so it would be nice to have something dynamic for water. This could be either something like the NLCD, which would give us a handful of time points or maybe we can directly ID water from remote sensing and get it out of either MODIS or (better yet) AVHRR.

> 2) While I'm at it, do we want to include any of the other land cover categories too? Should I just include all of them?

I think it's definitely worth getting all of the land cover categories out of any land cover data we look at since we also need them for #11.

**Comment by davharris** [comment]
Ah, right.  Forgot about PRISM's spatial limits. I'm not aware of anything updated more frequently at a national level than NLCD. I've been having trouble navigating the data repositories at FWS and USGS without much success.  I'll see what I can do.

**Comment by davharris** [comment]
For posterity, here's the code I used for NALCMS

```
library(dplyr)
library(raster)

landcover = raster("data/Land_Cover_2005v2_TIFF/LandCover_2005v2/data/NA_LandCover_2005V2_25haMMU.tif")
database = src_sqlite("data/bbsforecasting.sqlite")


locations = tbl(database, "bbs_data") %>% 
  select(long, lat) %>% 
  distinct() %>% 
  as.data.frame() %>%
  SpatialPoints(proj4string = CRS("+proj=longlat")) %>%
  spTransform(crs(landcover))



route_length = 39428.93 # 24.5 miles in meters

water_class = 18

percent_water = raster::extract(landcover, 
                                locations, 
                                buffer = route_length, 
                                fun = function(x){100 * mean(x == water_class)}
)
```
