### ISSUE TITLE
Add data on time of survey relative to sunrise

### ISSUE THREAD

**Issue by ethanwhite** [weecology/bbs-forecasting#29]
As an alternative to removing noctural/crepuscular species @davharris has suggested adding a variable describing the time of the survey relative to sunrise.

**Comment by davharris** [comment]
So I get to deal with spatial data *and* dates *and* times for this, including time zones. Hopefully I won't have to deal with too much of [this kind of nonsense](http://earthscience.stackexchange.com/a/7142)

* [Options for getting time zones for all the locations](http://stackoverflow.com/a/16086964/783153)
* Options for calculating sunrise/dawn/etc
   * There are a bunch of packages on CRAN that include these functions.  I remember checking into this a few years ago with a collaborator; she's going to get back to me soon with information on which package we ended up using.
   * For more accuracy, we could use [PyEphem](http://rhodesmill.org/pyephem/rise-set.html), which takes atmospheric effects into account and . See also: [examples on stack exchange](https://stackoverflow.com/questions/2637293/calculating-dawn-and-sunset-times-using-pyephem).
* We should also look into whether we want dawn, twilight, sunrise, etc. If I remember correctly, several of those terms also have several definitions. Probably best to just ask a few birders what they use.

**Comment by ethanwhite** [comment]
Won't happen in near future so closing.
