### ISSUE TITLE
oddball species

### ISSUE THREAD

**Issue by davharris** [weecology/bbs-forecasting#35]
How do we want to handle oddball "species" (e.g. unidentified species, hybrid species & subspecies)? They're usually pretty identifiable in the data using regexes, but it's not obvious to me how best to handle them.  

My proposal: 

* For subspecies, it might be best to lump them in with the rest of their species.
* For hybrids and unidentified species, we might have to drop them.  

On a related note, did we make a decision somewhere about whether to remove super-rare species from the data set?

**Comment by ethanwhite** [comment]
Your proposal sounds good to me.

Do we need to drop the super-rare's for the species distribution modeling?

**Comment by davharris** [comment]
We’d have to treat them specially in some way, either by fitting a different model with many fewer degrees of freedom or by dropping them altogether, I think.  Dropping them is simplest from my perspective.

**Comment by ethanwhite** [comment]
I have no objections.

**Comment by davharris** [comment]
So, I just had a revelation: rare species don't contribute very much to richness.

For example, there are 72 species that showed up 50 or fewer times in the training data; removing them would only change the average richness from 57.26 to 57.19.  

So (as long as we only care about richness) it shouldn't matter what we do with them. I'll just leave them in.

**Comment by ethanwhite** [comment]
Sounds good. There are some papers we can cite for this as well if we need them.
