### ISSUE TITLE
Move all database work to either SQLite or PostgreSQL

### ISSUE THREAD

**Issue by ethanwhite** [weecology/bbs-forecasting#38]
We currently have one (and maybe soon 2) calls to a postgres database. Since we're already using SQLite to store and pass around environmental data we should go ahead and add the BBS data to that database as well and extract it from there.

**Comment by davharris** [comment]
Oh, I was all excited to use PostGIS for faster buffer cutting with the NLCD data now that I've basically gotten all of this nonsense working.  But running raster::extract overnight is probably just as good, so I have no objections.

**Comment by ethanwhite** [comment]
Yeah, it's a tradeoff with ease of reproducibility. I think we should pick either Postgres or SQLite. SQLite will be easier for others since it doesn't require installing anything extra, but I'm OK with having an opinionated dependency here as well.

Also to consider when we're making this decision: @sdtaylor has just finished creating a more efficient version of extract for use with buffers that is apparently quite a bit faster.

**Comment by davharris** [comment]
Whoa, nice @sdtaylor

**Comment by ethanwhite** [comment]
I've updated the title to reflect a broader conversation about this. Thoughts on which DBMS we'd like to use throughout?

Major tradeoff: more power/speed with Postgres, but requires users to install and get PostgreSQL working in a way that the code can easily access the database (which as @davharris has experienced can be a bit of work).

**Comment by sdtaylor** [comment]
My extract with buffer improvement is only  faster when you have many rasters of the same data. Like prism or bioclim. For a single raster it shouldn't be any better than just extract(). NLCD has 3 or 4 version though, so it would help some there.

**Comment by davharris** [comment]
If we don’t need PostGIS for this project and the data sets don’t get any bigger, I don’t see any upside to using psql.

**Comment by ethanwhite** [comment]
> My extract with buffer improvement is only faster when you have many rasters of the same data. Like prism or bioclim. For a single raster it shouldn't be any better than just extract(). NLCD has 3 or 4 version though, so it would help some there. 

Ah, got it. Thanks for the clarification @sdtaylor.

> If we don’t need PostGIS for this project and the data sets don’t get any bigger, I don’t see any upside to using psql.

OK, if @sdtaylor is on board with this then let's proceed with SQLite and swap it out in the future if we end up needing more power.

**Comment by sdtaylor** [comment]
@ethanwhite have you done anything with this? I have to play around with this part of the code anyway in #61 so I thought I would switch things to sqlite while I'm at it.

**Comment by ethanwhite** [comment]
Go for it. Thanks.

**Comment by davharris** [comment]
I think this could be really helpful—especially because we might be able to do a lot of the joins and stuff before the data even hits R.

Thanks for looking into this!

**Comment by sdtaylor** [comment]
#66 done, and working without issue for a while.
