### ISSUE TITLE
Stop the namespace madness

### ISSUE THREAD

**Issue by davharris** [weecology/bbs-forecasting#39]
I see at least four options for dealing with all the namespaces clobbering each other

1) Leave all the `library` calls and add `::` where needed

2) Use `::` everywhere

3) Use explicit namespaces using R's package infrastructure

4) Use [the `import` package](https://github.com/smbache/import)

I'm leaning toward 3.  Thoughts @ethanwhite @sdtaylor?

**Comment by sdtaylor** [comment]
Does #3 involve putting @import inside the function definitions? If so I like that as well.

**Comment by davharris** [comment]
Above the function definitions (if we use roxygen), but yes.

Although it looks like I might have been wrong on Wednesday, and we might need to be consistent across the whole project about what namespace to pull functions like `select` and `extract` from.  I don’t expect there to be many conflicts though.

**Comment by ethanwhite** [comment]
Can you given an example of what option 3 looks like.

**Comment by davharris** [comment]
It’s pretty straightforward, I think. Here’s an example from mistnet2

> https://github.com/davharris/mistnet2/blob/0d6d230e057a7bfe0f115a526a64d64a9eee58cf/R/fit.R#L43 <https://github.com/davharris/mistnet2/blob/0d6d230e057a7bfe0f115a526a64d64a9eee58cf/R/fit.R#L43>

roxygen (via `devtools::document()`) automatically takes those tags and adds them to the NAMESPACE file like so:

> https://github.com/davharris/mistnet2/blob/master/NAMESPACE#L38-L47 <https://github.com/davharris/mistnet2/blob/master/NAMESPACE#L38-L47>

We’d also list the packages on the DESCRIPTION page:

> https://github.com/davharris/mistnet2/blob/master/DESCRIPTION#L20-L23 <https://github.com/davharris/mistnet2/blob/master/DESCRIPTION#L20-L23>

That’s it.

**Comment by davharris** [comment]
Oh, and using the package infrastructure would also mean we wouldn't need to `source` individual files to grab all our functions: we could just grab every function in the `R` directory at once with `devtools::load_all()`.

**Comment by davharris** [comment]
Oh, the link I meant to include in "here's an example from mistnet2" didn't actually link. 

[Here's an actual link.](https://github.com/davharris/mistnet2/blob/0d6d230e057a7bfe0f115a526a64d64a9eee58cf/R/mistnet.R#L22-L23)

**Comment by ethanwhite** [comment]
OK, I'm happy to try something new. Feel free to go ahead and implement 3.
