### ISSUE TITLE
train-test split

### ISSUE THREAD

**Issue by davharris** [weecology/bbs-forecasting#41]
What did we decide about the train-test split? Was it the last 5 years that were reserved for evaluation? Sorry if I'm just missing it---I don't see anything about it in either of the notebooks or in the core functions.

**Comment by ethanwhite** [comment]
Yes, it's the last 5 years. It should be the `lag` optional argument in the temporal forecasting function.

**Comment by ethanwhite** [comment]
I would also like to do a last 10 years analysis as well, so if we could run both that would be great.

**Comment by davharris** [comment]
Got it.  Thanks.
