### ISSUE TITLE
shear maps of SDM predictions

### ISSUE THREAD

**Issue by davharris** [weecology/bbs-forecasting#44]

**Comment by davharris** [comment]
Three species with different-looking distributions

**Comment by sdtaylor** [comment]
is this along the same lines as #8?

**Comment by davharris** [comment]
It's for Ethan's talk. He wanted maps that looked like the one I posted in #45.  We should be able to close this once that branch gets merged, I think.

**Comment by davharris** [comment]
(#8 is also covered by #45)

**Comment by davharris** [comment]
fixed in #77
