### ISSUE TITLE
Add threshold for maps

### ISSUE THREAD

**Issue by davharris** [weecology/bbs-forecasting#48]
if p<0.001?

**Comment by davharris** [comment]
Hi @ethanwhite, thanks for the great feedback today.

I played around with the map thresholding, but I'm not sure I like the result because both very dark purple and white indicate low probability. In the map below, it looks like a massive transition between black and nothing, even though it's just a difference between 0.00101 and 0.0099.

![image](https://cloud.githubusercontent.com/assets/843017/14891568/2f6d684e-0d35-11e6-91c9-ac46a2b64185.png)

How does this strike you instead? It uses the new perceptually-uniform "magma" palette.

![image](https://cloud.githubusercontent.com/assets/843017/14891606/5fff1da4-0d35-11e6-8635-c6dc9516acc8.png)

Or this, if you really want the tiny probabilities to disappear:

![image](https://cloud.githubusercontent.com/assets/843017/14891710/c590f4d0-0d35-11e6-9bd1-591717c69207.png)

Let me know which you prefer, and I'll push that one.

**Comment by davharris** [comment]
I think I got a good compromise in 057a6bcc55efcc4a376eb14de017df8874e702d0.  The background is less ugly and exact zeros are made invisible. Let me know what you think.

Continuous:

![image](https://cloud.githubusercontent.com/assets/843017/14900352/28155ad8-0d5e-11e6-9260-7fb29f3b80a8.png)


Discrete:

![image](https://cloud.githubusercontent.com/assets/843017/14900372/3cfe25c4-0d5e-11e6-9370-274ea08d9383.png)

**Comment by ethanwhite** [comment]
Looks great!

**Comment by davharris** [comment]
fixed in #77
