### ISSUE TITLE
fit a spatio-temporal model (if possible)

### ISSUE THREAD

**Issue by davharris** [weecology/bbs-forecasting#53]
One software package: https://github.com/James-Thorson/spatial_DFA

Also does JSDM (#52)

**Comment by sdtaylor** [comment]
Pretty sure this is the model used in [Ward et al 2016](http://onlinelibrary.wiley.com/doi/10.1890/15-0051.1/abstract) that I mentioned to @ethanwhite. *Really* awesome he made a package.

**Comment by ethanwhite** [comment]
The [Thorson et al. 2016](http://onlinelibrary.wiley.com/doi/10.1111/geb.12464/abstract) paper mentioned in the repo is also available now.

**Comment by ethanwhite** [comment]
Won't happen in near future so closing.
