### ISSUE TITLE
Decide on variable selection

### ISSUE THREAD

**Issue by davharris** [weecology/bbs-forecasting#55]
Better to do it once for all models than to let each model choose its own optimal predictors?

Certainly shouldn't let models see the test set when deciding which predictors to use...

**Comment by sdtaylor** [comment]
![bbs_sdm_importances](https://cloud.githubusercontent.com/assets/12282062/18918146/dc0e72dc-8567-11e6-80a2-fa61c32d0b13.png)

I ran daves sdm code from #76 and  pulled the variable importance from all the models. It's highly variable among species, but elevation has the biggest influence most of the time.

**Comment by davharris** [comment]
Nice.  I didn't put much thought into picking those variables, so we should probably do something a bit cleverer.  But this is definitely good to see.

As a side note, the version I just pushed saves this information (along with some other diagnostics) so it should be easier to do this sort of analysis in the future.

**Comment by davharris** [comment]
Mostly resolved: used the predictors from mistnet, plus NDVI and elevation.  Still need to figure out which subset of predictors to use in #24.
