### ISSUE TITLE
Convert PRISM data to bioclim

### ISSUE THREAD

**Issue by ethanwhite** [weecology/bbs-forecasting#6]
@sdtaylor - do you have code for this somewhere from your other work? If so, can you add a function for handling this to `get_prism_data.R`?

**Comment by sdtaylor** [comment]
Yes and yes.

**Comment by ethanwhite** [comment]
Thanks!

**Comment by sdtaylor** [comment]
I think get_prism_data can be cleaned up a bit. I imagine something like this:

function download_prism_data(){
   downloads the raw prism data
}

function get_prism_data(){
  if (data available in the sqlite DB)
       query that and return it
   else
       if (raw prism rasters are not available)
           runs download_prism_data() if the raw prism files aren't available. 
       extracts values from all prism files using BBS locations
       store them in the sqlite DB
       return extracted values
}

function process_bioclim_data(bbs_prism_values){
    process and return all bioclim from the prism values

function get_bioclim_data(){
    if (bioclim data available in sqlite DB)
        query that and return it
    else
         run get_prism_data()
         run process_bioclim_data()
         store bioclim data in sqlite DB
         return bioclim data      
}

**Comment by ethanwhite** [comment]
Looks like a great plan.

**Comment by sdtaylor** [comment]
#16 PR for this.

**Comment by ethanwhite** [comment]
Complete in #16.
