### ISSUE TITLE
Incorporate observer effects

### ISSUE THREAD

**Issue by davharris** [weecology/bbs-forecasting#61]
I'd feel better if I knew what was going on with big richness jumps like the one plotted below (site_id 27057).

![image](https://cloud.githubusercontent.com/assets/843017/17531609/ab2c577c-5e4a-11e6-94da-bde45bb2e014.png)

Is that a _real_ change in richness, or did a new observer just start counting the birds in 1993? These big jumps have a big impact on the tails of the random walk, so I think we'll want to see if we can understand them better.

My RPostgres isn't behaving at the moment, so I can't easily access the observer data right now.

**Comment by sdtaylor** [comment]
@ethanwhite has mentioned funny things around this time period too when using the env data. I thought it might be something to do with species name changes and our filtering of them, but I just checked the raw data downloaded by the retriever and it shows the same thing for this site. A new observer is probably the best explanation. But I will try to do a little detective work on this.

**Comment by davharris** [comment]
Thanks Shawn!

**Comment by ethanwhite** [comment]
Yeah, we should definitely do some digging on some of these rapid transitions. In general I think some time spent just looking through the compiled time-series and getting a feel for what sorts of things (weird and not so weird) are going on will be really useful.

Something else other than observer changes to look out for is any potential changes in the route. In concept I believe any change in the route is supposed to be accompanied by a change in the route number to avoid these issues, but I haven't looked into that in a while and could see it causing similar sorts of changes.

**Comment by sdtaylor** [comment]
For this site it is the observer changing over and counting more birds. here is the data for it from the BBS_weather file.

```
   year    obsn totalspp
1  1985  990081       42
2  1986  990081       38
3  1987  990081       49
4  1988  990081       43
5  1989  990081       39
6  1990  990081       37
7  1991  990081       33
8  1992 1010060       66
9  1993 1010060       63
10 1994 1010060       61
11 1995 1010060       63
12 1996 1010060       64
13 1997 1010060       64
14 1998 1010060       63
```

I'll look around and see how prevalent this is.

**Comment by davharris** [comment]
Thanks Shawn! I can start looking into adding an observer effect to my Stan code if this seems like it becomes a pattern.

Here are the 20 sites with the largest one-year jumps, in case a list is helpful.

61123
17003
91041
27057
91032
66033
72035
52002
46017
7020
72012
61045
58001
92019
81043
61064
58023
14151
91025
91012

**Comment by sdtaylor** [comment]
![bbs observers](https://cloud.githubusercontent.com/assets/12282062/17561597/d5f331f6-5ef4-11e6-8175-1c9b84d7f770.png)

Here is the richness time series for all the sites you mentioned. Note that I haven't filtered out waterfowl. The red lines are when a new observer started. This can definitely have an affect on the birds surveyed, but not always.

**Comment by davharris** [comment]
Nice work. 

Looks like we have a real effect, even if it isn't always large.  I think that adding this to the Stan model would be pretty easy, since it just affects the observation error and not the process error.

Would you be able to send a PR that adds observer ID as a new column? I think we could basically treat it like an environmental variable.

**Comment by ethanwhite** [comment]
Yes, definitely nice work! Very interesting.

> I think we could basically treat it like an environmental variable.

Is there any risk of this basically becoming a `site` effect in the spatial models? So, we say we're controlling for observer differences, but if each person generally does one BBS route there's a close mapping between `site` and `observer`? I don't think this matters for the current Stan model, but I'm just trying to think through the implications for our understanding if/when we apply this to other models.

**Comment by davharris** [comment]
All of the software I normally use for mixed models (i.e. Stan, lme4, and derivatives like gamm4) can handle random effects with both “nested” and “crossed” structure, so they should do "the right thing" in this case.  The closer the mapping is between observers and sites is to "one-to-one", the more uncertainty there will be, but nothing should outright break.

Does that answer your question?

**Comment by ethanwhite** [comment]
Thanks Dave. Yeah, that works. We can revisit come interpretation time if it comes up.

**Comment by sdtaylor** [comment]
> Would you be able to send a PR that adds observer ID as a new column?

Yep

**Comment by davharris** [comment]
@sdtaylor Once you add the observer column, could you email me any csv files in your `./data` folder? Postgres is being difficult on my machine. Thanks so much!

**Comment by davharris** [comment]
Papers/chapters on observer effects, via @ethanwhite:

https://sora.unm.edu/sites/default/files/journals/auk/v111n01/p0050-p0062.pdf
https://pubs.er.usgs.gov/publication/5210391

**Comment by ethanwhite** [comment]
I just updated the title to reflect the fact that we're now convinced that at least some of these are observer effects and we'd like to address them.
