### ISSUE TITLE
Daily weather variables

### ISSUE THREAD

**Issue by davharris** [weecology/bbs-forecasting#65]
Paper at: http://onlinelibrary.wiley.com/doi/10.1111/ecog.02321/full

R Package is on CRAN under the name "RFc"

Here's a list of what they have available (note that the NCEP/NCAR Reanalysis has 4x daily data going back to 1948 for temp and precip; `prate` is short for "precipitation rate").

Joan and I played with it a bit today, and the API seems very good (it's from Microsoft Research).

![image](https://cloud.githubusercontent.com/assets/843017/17714811/655a9dbe-63cf-11e6-8cb2-7c55aeb684d7.png)

Example script I used: 

`x = fcTimeSeriesDaily("airt", latitude = c(35, 36), longitude = c(-117, -118), firstYear = 1989)`

**Comment by ethanwhite** [comment]
Nice!

**Comment by sdtaylor** [comment]
Another option for weather data is [daymet](https://daymet.ornl.gov/).  
And a big advantage to either of these is being able to include all the Canada sites.

**Comment by ethanwhite** [comment]
Next time... perhaps.
