### ISSUE TITLE
Get longer-term NDVI data

### ISSUE THREAD

**Issue by ethanwhite** [weecology/bbs-forecasting#7]
Either landsat or AVHRR.

Initial work on this is started in `setup_ndvi_data.R` and the README in `./data/ndvidata/`. This uses NDVI data from AVHRR acquired from [EarthExplorer](http://earthexplorer.usgs.gov/). This data comes in already composited forms meaning they are relatively plug and play. Data goes back to 1989 and is available as GeoTIFF's.

[LTDR](http://ltdr.nascom.nasa.gov/cgi-bin/ltdr/ltdrPage.cgi) appears to provide daily NDVI data back to 1981 using a combination of AVHRR and MODIS data. Data is available [via FTP](ftp://ltdr.nascom.nasa.gov/allData/) as one `hdf` file/day (25-150 MB/file depending on the satellite) and are split up by satellite (with different satellites covering different time periods). The NDVI data is in the AVH13C1 files. [Description of the NDVI product](http://ltdr.nascom.nasa.gov/ltdr/docs/AVHRR_LTDR_V4_Document.pdf). Unfortunately these are daily data which would force us to do the compositing ourselves.

**Comment by ethanwhite** [comment]
There is an old R package that hypothetically helps with some of this, but it doesn't appear to have been touched in years and has been removed from CRAN. :sob:

**Comment by ethanwhite** [comment]
@skmorgane, @emchristensen, @davharris, @sdtaylor, @MarconiS: Any thoughts on the relative value/effort of these two different sources of data. My impression at the moment is that the LTDR data will be harder to work with (we'll have to handle creation of composites which I imagine will take a fair bit of work to do well and also probably quite a bit of computer time), but it also goes back an additional 8 years and the shift from 26-34 years of time-series is fairly substantial. Basically I'm contemplating where to invest time/energy given the tradeoffs and would value any thoughts you have on the matter.

**Comment by sdtaylor** [comment]
@ethanwhite  Is there a need to have something like 16-day NDVI composite images going back to 1981? Creating those images would be a lot of work, but extracting values for ~2000 points and compositing just that data seems easy enough.

**Comment by ethanwhite** [comment]
> Is there a need to have something like 16-day NDVI composite images going back to 1981? 

No, now that you mention it, for our purposes I think we just need to composite the points. So, there probably isn't a compute issue, but we'd still need to understand and code the rules for doing the compositing

**Comment by MarconiS** [comment]
8 years may be non negligible, indeed... but assuming a bunch of things I guess. We have to assume that the radiometer data collected by AVHRR2 were precise enough to be included in the same time series of AHVRR3 and/or MODIS, and that no artifact comes out of the composing/correcting. I am wondering how much higher uncertainty may grow doing the compositing by ourselves (if for compositing you mean cloud covering removal, and all kinds of corrections, otherwise sorry for the misinterpretation). For what I can grasp performing all the corrections is not only time consuming, but also "risky", especially if it involves only a subset of data (couldn't it lead to patterns driven by artifacts?)... In these cases, if I have enough data, I usually prefer to work with fewer but highly reliable ones (which I guess may be the case of 26  years long time series).

**Comment by ethanwhite** [comment]
The folks producing the LTDR data are, if I understand things correctly, supposed to be handling the differences between instruments to make the overall time-series comparable.

I agree with @MarconiS's concerns about the challenges of doing the compositing ourselves. We might want to bring in a remote sensing person to help with that if we go in that direction.

**Comment by sdtaylor** [comment]
@MarconiS It looks like LTDR already does a bunch of corrections for atmosphere, different satellites, and many other things. I can't find a definitive paper on it, but see this [presentation](http://ltdr.nascom.nasa.gov/ltdr/docs/AGU-Fall2009-vermote.pdf). The compositing on our end would just entail sub setting into the data into, for example, 16 day intervals so we get a decent amount of cloud free observations. 

The compositing algorithm looks very straightforward, according to [this document](http://modis.gsfc.nasa.gov/data/atbd/atbd_mod13.pdf), pg. 6. 

> The current procedure for generation of composited, AVHRR-based, NDVI products
is the maximum value compositing (MVC) technique.  This is accomplished by
selecting, on a pixel by pixel basis, the input pixel with the highest NDVI value as output
to the composited product.  The procedure generally includes cloud screening and data
quality checks

The LTDR data includes a QC flag for each pixel, which I'm guessing also has a value for clouds, but I will check on that.

**Comment by MarconiS** [comment]
Ok! I'll check it better in the next days; if you are right @sdtaylor, and it is not that complicated and/or time consuming, I guess it would be great to give it a try (it is about 30% increase in temporal horizon, and more than 30 years time series after all)! If you want @ethanwhite I can email a couple of researchers I've worked with in the past who are very strong in remote sensing stuff

**Comment by ethanwhite** [comment]
> If you want @ethanwhite I can email a couple of researchers I've worked with in the past who are very strong in remote sensing stuff 

Go for it. It would be great to get some external perspective on this.

**Comment by MarconiS** [comment]
Bad news and great news! 
Both Dario Papale and Gaia Vaglio Laurin suggested me not to try an improvised compositing of any remote sensing data; way too risky. However here comes the good news. 1) corrected data should already been found in the Gimms3 dataset for NDVI, LAI and fPAR (harmonization of the data done by Ranga Myani); 2) Frederic Baret worked on that in a very nice way years ago (Geoland-2 project). His site is down, but data were open access; hence we can try to contact him and ask harmonized data of our interest!

**Comment by sdtaylor** [comment]
Here is a really good [paper](http://www.sciencedirect.com/science/article/pii/S0034425711001957) comparing GIMMS, LTDR, and 2 other AVHRR products. Most of the paper says that all AVHRR prodcuts compares reasonably well to Landsat. But one of the last points definitely applies to what we're doing here. 

> The evaluation against Landsat–NDVI suggests that the LTDR V3 data set is the most accurate in terms of absolute values and the GIMMS data set the most accurate for assessing temporal change. MODIS–NDVI performed better than any AVHRR–NDVI data set.

Which means that, on a pixel to pixel comparison to the "true" landsat values, LTDR is better in a single time point. But on a pixel to pixel comparison comparing the difference between 2 time points, GIMMS was better. I'm not sure if they tested GIMMS v3, so it may better now in the 1st part.

**Comment by ethanwhite** [comment]
After some digging I think I've found monthly GIMMS data from 1981-2013:
http://ecocast.arc.nasa.gov/data/pub/gimms/

Other things I came across in the search: 

* GIMMS data, but only MODIS based so stopping in 2000. Maybe useful for filling in the last couple of years if comparable.
    * http://glam1.gsfc.nasa.gov/
    * ftp://gimms.gsfc.nasa.gov/MODIS/
* [Descriptions of data back to 1981](http://csdms.colorado.edu/wiki/Data:GIMMS), but with broken data links

**Comment by sdtaylor** [comment]
I just went from installing the gimms package to having the full ndvi time series for portal in about an hour (with the help of the hipergator), so +1 there for GIMMS.

**Comment by ethanwhite** [comment]
OK, given Sergio's colleague's recommendation, the paper Shawn found, and the ease of working with the data, let's go ahead and start with GIMMS for the time-being.

@sdtaylor, since you've got things working well already would you mind adding a function/script to extract the GIMMS data for all BBS routes in the SQLite database (or just all BBS routes). Let's go ahead and get all of the entire monthly time-series from 1981-present (or almost present) for each route.

**Comment by sdtaylor** [comment]
Yep, I'm on it.

**Comment by sdtaylor** [comment]
For GIMMS there is a little pre-processing that needs to be done. 

- There are bimonthly NDVI values. For our purposes I think we can just average them to get 1 value a month.
- It has a quality flag and it's mostly good across all years and sites. But a large chunk is 	`FLAG = 3 (NDVI retrieved from spline interpolation)` Which I think means a cloudy value was filled in using surrounding dates of the same pixel. I suspect it's probably fine to use. 

Should I average monthly values and filter out the bad flags in the get_ndvi script? Or would you rather that be done in the analysis scripts?

**Comment by sdtaylor** [comment]
and for future reference here is the official citations for GIMMS 3g,  [Pinzon & Tucker 2014](http://www.mdpi.com/2072-4292/6/8/6929/htm)

**Comment by ethanwhite** [comment]
> Should I average monthly values and filter out the bad flags in the get_ndvi script?

That would be great!

**Comment by ethanwhite** [comment]
I agree that for our purposes using the spline interpolation should be fine.

**Comment by sdtaylor** [comment]
#23 
This PR replaces MODIS NDVI with GIMMS. But there is still the potential to integrate MODIS back in somehow to fill in the years 2013+ that GIMMS doesn't have yet.

**Comment by ethanwhite** [comment]
Completed in #23. At some point we will want to come back and fill in 2013+ as @sdtaylor notes, but I'm going to go ahead and close this and replace with a more specific issue.
