### ISSUE TITLE
"speciestotal AS abundance", not "AS richness"?

### ISSUE THREAD

**Issue by davharris** [weecology/bbs-forecasting#70]
https://github.com/weecology/bbs-forecasting/blob/master/R/forecast-bbs-core.R#L160

richness would be more precise, I think?

**Comment by sdtaylor** [comment]
`speciestotal` in the counts file is the abundance of that species.  

Maybe your thinking of `TotalSpp` in `weather.csv` which is the richness.

**Comment by ethanwhite** [comment]
speciestotal in BBS is the abundance field for the entire route. That's 
one there's one per site per species.

**Comment by ethanwhite** [comment]
Oops, @sdtaylor beat me to it! The hazards of responding via email.

**Comment by davharris** [comment]
You're right.  Sorry for the mixup
