### ISSUE TITLE
inconsistent use of `species_id`

### ISSUE THREAD

**Issue by davharris** [weecology/bbs-forecasting#82]
[In the retriever, `species_id` refers to the column before `AOU`](https://github.com/weecology/retriever/blob/232c69911f7324d808b38a24fcf9d55f8e190a55/scripts/bbs.py#L49-L50). In this project, [we use](https://github.com/weecology/bbs-forecasting/blob/master/R/forecast-bbs-core.R#L159) `species_id` as a synonym for AOU.

What's the best way to avoid inconsistency when we try to do things like join the species table to the abundance table? We could change `get_species_data` with one line of code, but we'd still have this inconsistency between our database and our R code. Or we could change all instances of `species_id` to match the database, but that seems like a pain.

**Comment by ethanwhite** [comment]
Assuming the AOU's are all unique (which they should be), I'd probably vote for removing the `species_id` line from the Retriever scripts (both BBS and BBS50) since `AOU` is already the equivalent and more useful field for a primary key.

**Comment by davharris** [comment]
Should I file an issue/PR on the retriever?

**Comment by ethanwhite** [comment]
That would be great!

**Comment by davharris** [comment]
Actually, on further review, I think the earlier column could be useful.  Apparently, it contains the identifiers used in the "56th Supplement to AOU Check-list of North American Birds," which could be valuable for matching with other data sets. 

The identifiers in the `AOU` are only used for internal BBS purposes, and would thus be less useful for linking the data set to others.

(that's not a typo: the AOU's identifiers are in the `seq` column, and the BBS's internal identifiers are in the `AOU` column)

**Comment by ethanwhite** [comment]
Ah, I misread the code when looking at it as well. I have no strong feelings on how to manage this in our code.
