### ISSUE TITLE
test filter_species with combine_subspecies

### ISSUE THREAD

**Issue by davharris** [weecology/bbs-forecasting#83]
Currently, `filter_species` throws out anything with `unid.` in the name, on the theory that it can't be identified to species.  But the following three species (and possibly some others?) are identified to species, just not to subspecies.  I think that means we're throwing out observations for them incorrectly.

```
1    (unid. Red/Yellow Shafted) Northern Flicker
2                   (unid. race) Dark-eyed Junco
3 (unid. Myrtle/Audubon's) Yellow-rumped Warbler
```

**Comment by sdtaylor** [comment]
it looks like it's just those three species that are like this. I think this can be fixed by changing the filter to look at the `species` column instead of common names. If it's one we want to keep it will have just 1 name in the species column, while hybrids and unidentified  are like.

```
vociferus / arizonae
sp. 
platyrhynchos x rubripes or fulvigula
```

Just have to make sure it doesn't conflict with `combine_subspecies()`

**Comment by sdtaylor** [comment]
I need to clarify exactly what the species column represents. There are 5 possible types of entries. Ones with question marks I'm not sure about yet, even after looking thru the main metadata files. 

1.A single specific epithet. These are for birds identified to a single species
```
saya
rubinus
couchii
```
2.One to several specific epithets separated by a / . I think these are "unidentified but likely one of these"?
```
melancholicus / couchii
vociferans / verticalis
purpureus / cassinii / mexicanus
```
3.Two specific epithets separated by a space only. These should be subspecies?
```
jamaicensis harlani
herodias occidentalis
hyemalis hyemalis
```

4.Two specific epithets separated by a x. These should be hybrids? Note the 1st entry here looks like a hybrid of two subspecies. 
```
auratus auratus x auratus cafer
occidentalis x glaucescens
townsendi x occidentalis
```

5.Just an sp. These are identified only to genus
```
sp.
sp.
```

**Comment by ethanwhite** [comment]
@sdtaylor I believe that your interpretation is correct, but I'm looping in @ahhurlbert so that he can confirm.

**Comment by davharris** [comment]
I agree with all 5 of those.  

We're currently discarding slash-separated epithets (2) using `filter_species`. 

We're dropping subspecies names (3) and dumping them into their parent species using `combine_subspecies`.  

We also throw out all hybrids (4) and `sp.`s (5) with `filter_species`; I think we may be incorrectly throwing out the subspecies-level hybrid.

I don't see any question marks when I use `db_engine(action = 'read', sql_query = 'SELECT * FROM bbs_species')` though?

**Comment by ahhurlbert** [comment]
You guys sound like you've got it under control. As @davharris said, you'll want to make sure you're not throwing away "subspecies hybrids" like `auratus auratus x auratus cafer`.

**Comment by sdtaylor** [comment]
@davharris I meant the question marks in my comment.

**Comment by davharris** [comment]
I'll take a look at the subspecies-level hybrids now.

**Comment by sdtaylor** [comment]
The one above is the only hybrid + subspecies I could find. I've almost got a PR for this, just need to fine tune the regex

**Comment by davharris** [comment]
Ok, cool. I'll stop. 

Are you also fixing the 3 "unid." subspecies? Because I'm close to fixing that one. 

Dave

**Comment by sdtaylor** [comment]
Yeah, since those are identified to species in the `species` column they'll get included.

**Comment by davharris** [comment]
Okay, looks like you're right and the "English common name" column isn't needed.  Nice work.
