### ISSUE TITLE
Remove poorly sampled species from BBS data

### ISSUE THREAD

**Issue by ethanwhite** [weecology/bbs-forecasting#9]
The current BBS data includes water birds and nocturnal species that aren't sampled well. They need to be removed.

**Comment by davharris** [comment]
Is trait-based removal better than frequency-based removal? In the past, I've always just excluded the species that didn't occur at least x times in the training data.

**Comment by ethanwhite** [comment]
Trait-based is generally considered the best way to go based on both what's in the literature and in talking to folks who are both birding and data experts. Many reviewers of BBS related analyses will consider this to be a crucial step. That said, I suspect that it won't make much difference either way in this context.

**Comment by sdtaylor** [comment]
#42  Removed poorly sampled species according to the [data wiki suggestion](http://ecologicaldata.org/wiki/breeding-bird-survey-north-america)

> Best practices
 For community analyses it is generally best to exclude nocturnal, crepuscular, and aquatic species as they are not well sampled. (That is, exclude AOU species codes <=2880 [waterbirds, shorebirds, etc], (>=3650 & <=3810) [owls], (>=3900 &  <=3910) [kingfishers], (>=4160 & <=4210) [nightjars], 7010 [dipper].)
    Surveys where RunType in the Weather table is 0 should be excluded as this indicates a survey that does not pass quality standards.
    Only use the Run Protocol IDs (counts.RPID) that are appropriate for your study. If you just want standard BBS surveys, use RPID = 101.
