### ISSUE TITLE
Make graphs that compare predictions of future state to predictions of changes 

### ISSUE THREAD

**Issue by ethanwhite** [weecology/bbs-forecasting#91]
This is potentially a nice way to communicate what the benchmark comparisons tell us.

I'm basically envisioning an observed-predicted plot of forecast vs. observed richness side-by-side with an observed-predicted plot of forecast change in richness vs. observed change in richness. The first will look good and demonstrates that if we just need to know what richness will look like in 20 years, we do that, but the second will look bad showing that we don't really benefit from the more sophisticated models over just assuming that things don't change.

This ties back to the results in [Rapacciuolo 2012](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0040212), which shows that SDMs work well for forecasting species locations because they are good at predicting the areas that don't change.

**Comment by davharris** [comment]
Is this issue still active, @ethanwhite?

**Comment by ethanwhite** [comment]
I think we've covered the same idea in other ways.
