### ISSUE TITLE
Predict with 10 years' training data

### ISSUE THREAD

**Issue by ethanwhite** [weecology/bbs-forecasting#97]
I'm thinking about adding a longer-term forecast analysis to push the longest forecast out to 20+ years so that we get a better idea of whether the spatial and time-series approaches really end up converging. I'm envisioning leaving the bulk of the analysis as is, but adding one additional analysis where we train on the first 5-10 years and forecast on the last 20-25.

**Comment by sdtaylor** [comment]
If it's done using the just the time series models we can use a larger dataset. Say from 1970-2015. That would  give 20-25 years for both training and testing.

**Comment by ethanwhite** [comment]
I think we can do it for all the space-for-time models as well, so the SDMs, JSDMs, and richness-env models.

**Comment by ethanwhite** [comment]
We decided to do a run with 10 years of training and 20 years of test.

**Comment by ethanwhite** [comment]
We didn't get to this for the first paper. It has now been included in #176.
